In [9]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [14]:
!pip install word2number
from word2number import w2n


  Using cached word2number-1.1-py3-none-any.whl


In [16]:
df=pd.read_csv("/content/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9       5000
1        NaN                    8.0                           6       4500
2       five                    6.0                           7       6000
3        two                   10.0                          10       6500
4      seven                    9.0                           6       7000
5      three                    7.0                          10       6200
6        ten                    NaN                           7       7200
7     eleven                    7.0                           8       8000

In [17]:
med=df['test_score(out of 10)'].median()


In [18]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(med)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9       5000
1        NaN                    8.0                           6       4500
2       five                    6.0                           7       6000
3        two                   10.0                          10       6500
4      seven                    9.0                           6       7000
5      three                    7.0                          10       6200
6        ten                    8.0                           7       7200
7     eleven                    7.0                           8       8000

In [19]:
df.experience=df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9       5000
1       zero                    8.0                           6       4500
2       five                    6.0                           7       6000
3        two                   10.0                          10       6500
4      seven                    9.0                           6       7000
5      three                    7.0                          10       6200
6        ten                    8.0                           7       7200
7     eleven                    7.0                           8       8000

In [20]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9       5000
1           0                    8.0                           6       4500
2           5                    6.0                           7       6000
3           2                   10.0                          10       6500
4           7                    9.0                           6       7000
5           3                    7.0                          10       6200
6          10                    8.0                           7       7200
7          11                    7.0                           8       8000

In [21]:
df['salary($)']=df['salary($)']*10

In [22]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [23]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [33]:
reg.intercept_

1773.7263464337711

In [24]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

joblib n pickel are used to turn files or model into binary so that they can be shared or load model when needed


In [40]:

import joblib


In [42]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [43]:
mj=joblib.load('model_joblib')

In [44]:
mj.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [26]:
import pickle

 with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [29]:
 with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [32]:
 with open('model_pickle','rb') as f:
  mp= pickle.load(f)

In [34]:
mp.predict([[7,8,9]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([72040.75691412])